### PR TITLE
using sharp to convert image color-space to rgb for webp

### LINKED ISSUE #1330: Don't retry to download if the image optimization fails
It looks like that if the conversion fails, then it retries to download:
```
[log] [2020-12-11T04:21:24.988Z] Not able to download content for https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Second_Avenue_Subway_Map_vc.jpg/300px-Second_Avenue_Subway_Map_vc.jpg due to Error: Unsupported color conversion request
Error! Could not process file /dev/shm/306e87e6-8f4d-44e3-9ae6-be9c3c4ca265
Error! Cannot read input picture file '/dev/shm/306e87e6-8f4d-44e3-9ae6-be9c3c4ca265'

[log] [2020-12-11T04:21:24.989Z] Not able to download content for https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/LOGO_HAEMMERLIN.jpg/550px-LOGO_HAEMMERLIN.jpg due to Error: Unsupported color conversion request
Error! Could not process file /dev/shm/9a1dc743-6783-4410-b3db-5513b8d0b6cf
Error! Cannot read input picture file '/dev/shm/9a1dc743-6783-4410-b3db-5513b8d0b6cf'

[log] [2020-12-11T04:21:31.931Z] Not able to download content for https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/LOGO_HAEMMERLIN.jpg/550px-LOGO_HAEMMERLIN.jpg due to Error: Unsupported color conversion request
Error! Could not process file /dev/shm/876eefa9-4027-4641-a24f-01f10a53caa5
Error! Cannot read input picture file '/dev/shm/876eefa9-4027-4641-a24f-01f10a53caa5'

[log] [2020-12-11T04:21:33.042Z] Not able to download content for https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Second_Avenue_Subway_Map_vc.jpg/300px-Second_Avenue_Subway_Map_vc.jpg due to Error: Unsupported color conversion request
Error! Could not process file /dev/shm/531f50c0-6fbc-48ef-8543-144cb8467f2b
Error! Cannot read input picture file '/dev/shm/531f50c0-6fbc-48ef-8543-144cb8467f2b'

[log] [2020-12-11T04:21:40.101Z] Not able to download content for https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/LOGO_HAEMMERLIN.jpg/550px-LOGO_HAEMMERLIN.jpg due to Error: Unsupported color conversion request
Error! Could not process file /dev/shm/6265d7df-bf88-41d3-a4a8-f181e255326c
Error! Cannot read input picture file '/dev/shm/6265d7df-bf88-41d3-a4a8-f181e255326c'

[log] [2020-12-11T04:21:44.847Z] Not able to download content for https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Second_Avenue_Subway_Map_vc.jpg/300px-Second_Avenue_Subway_Map_vc.jpg due to Error: Unsupported color conversion request
Error! Could not process file /dev/shm/1c43e0fc-72a9-4964-9bff-aba5d4cbb0ef
Error! Cannot read input picture file '/dev/shm/1c43e0fc-72a9-4964-9bff-aba5d4cbb0ef'

[log] [2020-12-11T04:21:50.708Z] Not able to download content for https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/LOGO_HAEMMERLIN.jpg/550px-LOGO_HAEMMERLIN.jpg due to Error: Unsupported color conversion request
Error! Could not process file /dev/shm/0f274932-7924-4064-aa95-154e4b1b5a5f
Error! Cannot read input picture file '/dev/shm/0f274932-7924-4064-aa95-154e4b1b5a5f'

T:254882; A:4943000; RA:1; CA:2275010; UA:2667989; FA:0; IA:2274938; C:34785; CC:25945; UC:8840; WC:0
[log] [2020-12-11T04:22:00.197Z] Not able to download content for https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Second_Avenue_Subway_Map_vc.jpg/300px-Second_Avenue_Subway_Map_vc.jpg due to Error: Unsupported color conversion request
Error! Could not process file /dev/shm/a157bd72-cc3f-43cb-9f62-f2865e985364
Error! Cannot read input picture file '/dev/shm/a157bd72-cc3f-43cb-9f62-f2865e985364'

[log] [2020-12-11T04:22:11.262Z] Not able to download content for https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/LOGO_HAEMMERLIN.jpg/550px-LOGO_HAEMMERLIN.jpg due to Error: Unsupported color conversion request
Error! Could not process file /dev/shm/bbd3e561-72b4-476b-9d84-45828564cbbd
Error! Cannot read input picture file '/dev/shm/bbd3e561-72b4-476b-9d84-45828564cbbd'

```

We should avoid that. Instead we should abandon this image and report properly.

### PR DESCRIPTION
**Pull request by MananJethwani**
this resolves #1330

### CODE REVIEW

**Comment by tim-moody** [comment]
There are typically 1 in 10 errors that are status 404 or 400. Not sure if you are trapping for those as well.

**Comment by kelson42** [comment]
@tim-moody This PR is conceived to fix #1330. What you talk about is something different.

**Comment by tim-moody** [comment]
@kelson42 it looks to me like the code catches all image retrieval errors, but only handles the color conversion one, so the question is whether the PR is for handling color conversions and does too much or handling image errors and does too little. obviously your choice. (or I misunderstood the code.)

**Comment by kelson42** [comment]
@tim-moody It is still a work in progress.

File: src/Downloader.ts [hunk 1]
```diff
@@ -611,7 +612,14 @@ class Downloader {
     if (isBitmapImageMimeType(resp.headers['content-type'])) {
       if (isWebpCandidateImageMimeType(this.webp, resp.headers['content-type']) &&
           !this.cssDependenceUrls.hasOwnProperty(resp.config.url)) {
-        resp.data = await imagemin.buffer(resp.data, imageminOptions.get('webp').get(resp.headers['content-type']));
+        resp.data = await imagemin.buffer(resp.data, imageminOptions.get('webp').get(resp.headers['content-type']))
+        .catch( async (err) => {
+          if (/Unsupported color conversion request/.test(err.stderr)) {
+            return await imagemin.buffer(await sharp(resp.data).toColorspace('srgb').toBuffer(), imageminOptions.get('webp').get(resp.headers['content-type']));
+          } else {
+            return await imagemin.buffer(resp.data, imageminOptions.get('default').get(resp.headers['content-type']));
```
Comment (kelson42) [inline src/Downloader.ts:620]: The content-type should be set earlier and if the conversion failed, it should be not set to webp. Unfortunately we have anyway to keep webp extension otherwise we will have broken links.

File: test/unit/downloader.test.ts [hunk 2]
```diff
@@ -56,6 +57,9 @@ test('Downloader class', async (t) => {
     const contentRes = await downloader.downloadContent(`https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/London_Montage_L.jpg/275px-London_Montage_L.jpg`);
     t.ok(!!contentRes.responseHeaders, 'downloader.downloadContent returns');
 
+    const {content} = await downloader.downloadContent(`https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/LOGO_HAEMMERLIN.jpg/550px-LOGO_HAEMMERLIN.jpg`);
+     t.equal((await FileType.fromBuffer(Buffer.from(content))).mime, 'image/webp', 'Webp compression wroking for cmyk color-space images')
```
Comment (kelson42) [inline test/unit/downloader.test.ts:61]: Small typo in the message

**Review by kelson42 — APPROVED** [review]
