### PR TITLE
Automatically guess / retrieve mediawiki paths

### LINKED ISSUE #2399: Add support for (chinese) variants
Some wikis like zh.wikipedia.org do support variants.

In https://github.com/openzim/mwoffliner/issues/840, we will do the necessary to at least be consistent in the variant we use in a ZIM.

Once done, we will have to decide how we want to support variants in mwoffliner ZIMs (especially for zh.wikipedia.org).

### LINKED ISSUE #2422: Automatically guess / retrieve mediawiki paths
Currently, one needs to configure `mwUrl` and adjust `mwWikiPath`, `mwIndexPhpPath`, `mwActionApiPath`, `mwRestApiPath`, and `mwModulePath`.

We should find a way to guess or retrieve these paths automatically, there is just too much room for error here, especially `mwWikiPath` and `mwIndexPhpPath` which could be wrong without the scrapper really noticing until many links get broken.

To be investigated, looks like these are not exposed in an API. Some can be found on `Special:Version` page but HTML needs to be parsed, and some are missing on this page, and not all values are easy to adjust correctly. For instance on https://minecraft.wiki/w/Special:Version, we have `articlePath` set to `/w/$1` which means that `mwWikiPath` is `/w/`, and `index.php` set to `/` which means that `mwIndexPhpPath` is `/index.php` ... not really straightforward conversions. But maybe we don't have anything better. 

Note this is a enhancement related to https://github.com/openzim/mwoffliner/issues/2421 (which should be implemented first since this is a kind of bug)

### PR DESCRIPTION
**Pull request by Markus-Rost**
Fix #2422
Fix #2399

- Remove `mwWikiPath` and `mwIndexPhpPath` CLI parameter, use values from the API instead
- Build `mwRestApiPath` and `mwModulePath` CLI parameter default values from the API
- Add `langVariant` CLI parameter for language conversion
  - Medium term fix for #2399, this replaces the temporary fix for #840

### CODE REVIEW

**Comment by kelson42** [comment]
I won't make the full review, but I would be carreful about proposing PR fixing many different things at the same time.

I would recommend to multiple PR, with each one based on the branch of the other.

**Comment by Markus-Rost** [comment]
> I won't make the full review, but I would be carreful about proposing PR fixing many different things at the same time.
> 
> I would recommend to multiple PR, with each one based on the branch of the other.

I'll see if I can split them, however at least `langVariant` and the path options are in the same area and therefore can't be split

**Comment by Markus-Rost** [comment]
Test currently fails due to #2468 so we need to merge #2469 first

**Comment by benoit74** [comment]
@Markus-Rost regarding `langVariant`, do I get it correctly that with this PR merged: 
- if we do not pass `--langVariant`, we will have "original" content, probably mixing multiple variants on WPZH, just like before `1.16.0`
- if we pass `--langVariant zh-cn` to WPZH, we will get the same result as `1.16.0`

**Comment by Markus-Rost** [comment]
> @Markus-Rost regarding `langVariant`, do I get it correctly that with this PR merged:
> 
> * if we do not pass `--langVariant`, we will have "original" content, probably mixing multiple variants on WPZH, just like before `1.16.0`
> * if we pass `--langVariant zh-cn` to WPZH, we will get the same result as `1.16.0`

That is correct.

**Comment by benoit74** [comment]
@Markus-Rost please rebase + force push

**Comment by Markus-Rost** [comment]
> @Markus-Rost please rebase + force push

Done, tests now failing due to nodejs/node#59480

**Review by benoit74 — CHANGES_REQUESTED** [review]
Thank you very much, I really like the middle ground you achieved between guessing as much as possible but not guessing the impossible. Having to specify at least wiki URL + API location seems very reasonable.

I'm a bit concerned that removing the two CLI parameter are a breaking change from semantic versioning perspective, so we should rename 1.17.0 to 2.0.0 ; do you think we could postpone CLI parameter removal to later and only compute default values for the time being? I feel like it is a kind of additional burden. But breaking semantic versioning is not really good practice either. And I don't want to publish a 2.0.0 now since we will need a new major once we implement #2210. Or maybe it is time to implement #2210. @kelson42 WDYT, are you ready for #2210 now?

**Comment by Markus-Rost** [comment]
> do you think we could postpone CLI parameter removal to later and only compute default values for the time being?

How about marking them both as deprecated options which won't do anything anymore? That should prevent the change from being breaking

**Comment by kelson42** [comment]
Please keep the working options, update the usage(), and create issue to remove them in 2.0. All of this should be trivial. To me, we just have now a far better/smarter way to decide what to use if the user is not specific.

**Comment by kelson42** [comment]
> @Markus-Rost regarding `langVariant`, do I get it correctly that with this PR merged:
> 
> * if we do not pass `--langVariant`, we will have "original" content, probably mixing multiple variants on WPZH, just like before `1.16.0`
> * if we pass `--langVariant zh-cn` to WPZH, we will get the same result as `1.16.0`

We should probably corresponding issues for Zimfarm and Zim-requests, so recipes will be updated for mwoffliner 1.17.

**Comment by Markus-Rost** [comment]
> Please keep the working options, update the usage(), and create issue to remove them in 2.0. All of this should be trivial. To me, we just have now a far better/smarter way to decide what to use if the user is not specific.

I've marked the options as deprecated but kept them working. Should they be set to a value different from the path return by the api, a warning will be logged. I have create #2489 to remove them in 2.0

File: src/MediaWiki.ts [hunk 1]
```diff
@@ -497,14 +497,44 @@ class MediaWiki {
       return possibleLangPairs[0] || ['en', 'eng']
     })
 
-    this.skin = this.getDefaultSkin(body.query.skins)
+    // Use CLI parameter and set MediaWiki config
+    if (mwWikiPath) {
+      mwWikiPath = mwWikiPath + '$1'
+      if (mwWikiPath !== generalEntries.articlepath) {
+        logger.warn('mwWikiPath does not match the value returned by the wiki.')
```
Comment (benoit74) [inline src/MediaWiki.ts]: Please log both values as well, so that it is easier / faster to diagnose

File: src/MediaWiki.ts [hunk 2]
```diff
@@ -497,14 +497,44 @@ class MediaWiki {
...
+      }
+    }
+    const articlepath = mwWikiPath || generalEntries.articlepath
+    if (articlepath.includes('?') || !articlepath.endsWith('$1')) {
+      throw new Error(`Article path [${articlepath}] is not supported`)
+    }
+    this.wikiPath = articlepath.replace('$1', '')
+    if (mwIndexPhpPath && mwIndexPhpPath !== generalEntries.script) {
+      logger.warn('mwIndexPhpPath does not match the value returned by the wiki.')
```
Comment (benoit74) [inline src/MediaWiki.ts]: Please log both values as well, so that it is easier / faster to diagnose

**Comment by benoit74** [comment]
> We should probably corresponding issues for Zimfarm and Zim-requests, so recipes will be updated for mwoffliner 1.17

This is part of the release process. No need to open a specific issue for now. At release, I will just like usually create a Zimfarm PR to adjust flags, update recipes to adjust existing settings, update mwoffliner wiki, ...
