### PR TITLE
Fix for 404 pages on fr wiktionary

### LINKED ISSUE #989: Sample custom plugin for wiktionary
In order to produce better wiktionary ZIM ([#147](/openzim/zim-requests/issues/147) [#148](/openzim/zim-requests/issues/148)), we need to be able to manipulate the received DOM for each article.

This is why #941 was opened: to allow custom article DOM processing in mwoffliner through a plugin mechanism. Discussion about how to implement this mechanism is up to #941 so I am documenting here a sample requirement for the *demo wiktionary plugin* we'll use to bootstrap the feature.

### Main objective

* simplify [fr-wiktionary](https://fr.wiktionary.org) ZIM with french-only info.
* ideally it should work with all wiktionaries but for this use case, we'll test over FR version.
* the *target* language would be the main wiktionary language (FR in this case) but we might want to keep it an option to extract specific foreign-to-french language ZIM (BM-FR or IT-FR for instance).
* in this regard, we might want to set a list of languages to keep? @kelson42 @Popolechien what do you think?
  * In `fr`, we might need to include `fro` (Ancien français)…
* articles without a section of the target language(s) should not be included.
  * Ex: with `fr` target, [buru article](https://fr.wiktionary.org/wiki/buru) should not be included.
* the TOC should be removed if we have a single language target and reduced if not.
* only the target-language(s) section(s) should be kept.
* in-section content should be kept as is.

### DOM Manipulations

* [pain](https://fr.wiktionary.org/wiki/pain) is a good example
* we'll need a mapping for `targetLanguage(s)` to `#AnchorLink(s)` as this is what's usable (in the rendered version).
* `h1#firstHeading` is kept
* rest happens solely within `div.mw-parser-output`
* if we can know that `div.bandeau-voir` will not have valid links, remove it. (otherwise, it will be a link-less sentence). this classname being french, I bet it's specific.
* if `div#toc > ul li a[href]` (without `#`) is not in our `anchorLinks` then the whole `li` is removed.
* if there's only `div#toc > ul > li` left, then remove `div#toc`
* if there's no `div#toc > ul > li`, then the page doesn't contain wanted content and should not be included.
* for the rest of the article, if `h2 > span.mw-headline[id]` not in `anchorLinks` then every elements from that `h2` up to the next `h2` (or end of `div.mw-parser-output`)

### PR DESCRIPTION
**Pull request by bakshiutkarsha**
should resolve #989

### CODE REVIEW

**Comment by bakshiutkarsha** [comment]
> The whole approach around `articleList` seems wrong. Why having an additional list? Articles which won't be mirrored should be removed in the Redis and all the rest should just work fine.

Thanks for the review, the code looks much simpler now.

**Comment by bakshiutkarsha** [comment]
> > The whole approach around `articleList` seems wrong. Why having an additional list? Articles which won't be mirrored should be removed in the Redis and all the rest should just work fine.
> 
> Thanks for the comments, the code looks much simpler now.

File: extensions/wiktionary_fr.js [hunk 1]
```diff
@@ -8,7 +8,7 @@ module.exports = class WiktionaryFR { // implements CustomProcessor
         for (const title of nonFrenchTitles) {
             title.closest('details').remove();
         }
-
+
```
Comment (kelson42) [inline extensions/wiktionary_fr.js:11]: Pleae remove trailing spaces here.

File: src/util/saveArticles.ts [hunk 2]
```diff
@@ -118,26 +118,62 @@ async function downloadBulk(listOfArguments: any[], downloader: Downloader): Pro
...
-            {concurrency: CONCURRENCY_LIMIT}
+            { concurrency: CONCURRENCY_LIMIT }
         );
     } catch (err) {
         logger.log(`Not able download in bulk due to ${err}`);
     }
 }
 
+async function getAllArticlesToKeep(downloader: Downloader, mw: MediaWiki, dump: Dump) {
+    if (!dump.customProcessor) {
```
Comment (kelson42) [inline src/util/saveArticles.ts:129]: I would like to see this specific test outside the `getAllArticlesToKeep()` call.
Here, in place, I would like to check if `dump.customProcessor.shouldKeepArticle` function exists at all. We can have a customflavour which does not implement that function.

File: src/util/saveArticles.ts [hunk 3]
```diff
@@ -118,26 +118,62 @@ async function downloadBulk(listOfArguments: any[], downloader: Downloader): Pro
...
+                try {
+                    const rets = await downloader.getArticle(articleId, dump);
+
+                    for (const { articleId, html: articleHtml } of rets) {
+                        if (!articleHtml) {
+                            continue;
+                        }
+
+                        const { articleDoc: _articleDoc } = await processArticleHtml(articleHtml, downloader, mw, dump, articleId);
+                        const articleDoc = _articleDoc;
```
Comment (kelson42) [inline src/util/saveArticles.ts:145]: I don't believe this is necessary.

File: src/util/saveArticles.ts [hunk 4]
```diff
@@ -118,26 +118,62 @@ async function downloadBulk(listOfArguments: any[], downloader: Downloader): Pro
...
+            for (const [articleId] of Object.entries(articleKeyValuePairs)) {
+                try {
+                    const rets = await downloader.getArticle(articleId, dump);
+
+                    for (const { articleId, html: articleHtml } of rets) {
+                        if (!articleHtml) {
+                            continue;
+                        }
+
+                        const { articleDoc: _articleDoc } = await processArticleHtml(articleHtml, downloader, mw, dump, articleId);
```
Comment (kelson42) [inline src/util/saveArticles.ts:144]: Why we do `processArticleHtml`, seems not necessary here to me.

File: src/util/saveArticles.ts [hunk 5]
```diff
@@ -118,26 +118,62 @@ async function downloadBulk(listOfArguments: any[], downloader: Downloader): Pro
...
+                        const articleDoc = _articleDoc;
+
+                        if (dump.customProcessor?.shouldKeepArticle) {
```
Comment (kelson42) [inline src/util/saveArticles.ts:147]: Like I said earlier, this test should be done earlier (only one time).

File: src/util/saveArticles.ts [hunk 6]
```diff
@@ -118,26 +118,62 @@ async function downloadBulk(listOfArguments: any[], downloader: Downloader): Pro
...
+                            const shouldContinue = await dump.customProcessor.shouldKeepArticle(articleId, articleDoc);
+                            if (!shouldContinue) {
+                                await articleDetailXId.delete(articleId);
+                            }
```
Comment (kelson42) [inline src/util/saveArticles.ts:151]: There is probably a more elegant manner to code this (in one line). Considering that we don't expect anything from the `delete()` I don't believe this is necessary to have an `await` here.

File: src/util/saveArticles.ts (hunk 4 above)
Comment (bakshiutkarsha) [reply src/util/saveArticles.ts:141]: We need _articleDoc to perform operations on it. For eg: `doc.querySelector(`#fr.sectionlangue`);`
 `articleHtml` is a type string, we need to process it in doc to use methods on it.

Comment (kelson42) [reply src/util/saveArticles.ts:141]: What you need is a DOM. To get the DOM from the HTML, you just need to call `let doc = domino.createDocument(html);` so why calling the most complex function of the whole MWoffliner instead of just calling that line?
